# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [1]:
import os
import numpy as np
import pandas as pd

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [2]:
lst_50 = [i for i in range(1,51)]

print(lst_50)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [3]:
lst_50 = [i for i in range(51) if i >= 1]

print(lst_50)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [4]:
lst_200 = [i for i in range(2,201,2)]

print(lst_200)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]


### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [5]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

print(a)

[[0.84062117 0.48006452 0.7876326  0.77109654]
 [0.44409793 0.09014516 0.81835917 0.87645456]
 [0.7066597  0.09610873 0.41247947 0.57433389]
 [0.29960807 0.42315023 0.34452557 0.4751035 ]
 [0.17003563 0.46843998 0.92796258 0.69814654]
 [0.41290051 0.19561071 0.16284783 0.97016248]
 [0.71725408 0.87702738 0.31244595 0.76615487]
 [0.20754036 0.57871812 0.07214068 0.40356048]
 [0.12149553 0.53222417 0.9976855  0.12536346]
 [0.80930099 0.50962849 0.94555126 0.33364763]]


In [6]:
lst = [x for i in a for x in i]

print(lst)

[0.84062117, 0.48006452, 0.7876326, 0.77109654, 0.44409793, 0.09014516, 0.81835917, 0.87645456, 0.7066597, 0.09610873, 0.41247947, 0.57433389, 0.29960807, 0.42315023, 0.34452557, 0.4751035, 0.17003563, 0.46843998, 0.92796258, 0.69814654, 0.41290051, 0.19561071, 0.16284783, 0.97016248, 0.71725408, 0.87702738, 0.31244595, 0.76615487, 0.20754036, 0.57871812, 0.07214068, 0.40356048, 0.12149553, 0.53222417, 0.9976855, 0.12536346, 0.80930099, 0.50962849, 0.94555126, 0.33364763]


In [7]:
# what it means
lst = []

for x in a:
    for y in x:
        lst.append(y)

print(lst)

[0.84062117, 0.48006452, 0.7876326, 0.77109654, 0.44409793, 0.09014516, 0.81835917, 0.87645456, 0.7066597, 0.09610873, 0.41247947, 0.57433389, 0.29960807, 0.42315023, 0.34452557, 0.4751035, 0.17003563, 0.46843998, 0.92796258, 0.69814654, 0.41290051, 0.19561071, 0.16284783, 0.97016248, 0.71725408, 0.87702738, 0.31244595, 0.76615487, 0.20754036, 0.57871812, 0.07214068, 0.40356048, 0.12149553, 0.53222417, 0.9976855, 0.12536346, 0.80930099, 0.50962849, 0.94555126, 0.33364763]


In [8]:
lst = [y for x in a for y in x]

print(lst)

[0.84062117, 0.48006452, 0.7876326, 0.77109654, 0.44409793, 0.09014516, 0.81835917, 0.87645456, 0.7066597, 0.09610873, 0.41247947, 0.57433389, 0.29960807, 0.42315023, 0.34452557, 0.4751035, 0.17003563, 0.46843998, 0.92796258, 0.69814654, 0.41290051, 0.19561071, 0.16284783, 0.97016248, 0.71725408, 0.87702738, 0.31244595, 0.76615487, 0.20754036, 0.57871812, 0.07214068, 0.40356048, 0.12149553, 0.53222417, 0.9976855, 0.12536346, 0.80930099, 0.50962849, 0.94555126, 0.33364763]


In [9]:
lst_lst = [[1,2,3], [4,5,6], [7,8,9]]

lst = [y for x in lst_lst for y in x]
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [10]:
print(lst_lst[0][2])

3


In [11]:
# how to search a particular value
print(lst_lst[0][1])

2


In [12]:
lst_lst[1][2]

6

### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [13]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

print(a)

[[0.84062117 0.48006452 0.7876326  0.77109654]
 [0.44409793 0.09014516 0.81835917 0.87645456]
 [0.7066597  0.09610873 0.41247947 0.57433389]
 [0.29960807 0.42315023 0.34452557 0.4751035 ]
 [0.17003563 0.46843998 0.92796258 0.69814654]
 [0.41290051 0.19561071 0.16284783 0.97016248]
 [0.71725408 0.87702738 0.31244595 0.76615487]
 [0.20754036 0.57871812 0.07214068 0.40356048]
 [0.12149553 0.53222417 0.9976855  0.12536346]
 [0.80930099 0.50962849 0.94555126 0.33364763]]


In [14]:
lst_05 = [x for i in a for x in i if x >= 0.5]

print(lst_05)

[0.84062117, 0.7876326, 0.77109654, 0.81835917, 0.87645456, 0.7066597, 0.57433389, 0.92796258, 0.69814654, 0.97016248, 0.71725408, 0.87702738, 0.76615487, 0.57871812, 0.53222417, 0.9976855, 0.80930099, 0.50962849, 0.94555126]


In [15]:
lst_ex = []

for i in a:
    for x in i:
        if x >= 0.5:
            lst_ex.append(x)
print(lst_ex)

[0.84062117, 0.7876326, 0.77109654, 0.81835917, 0.87645456, 0.7066597, 0.57433389, 0.92796258, 0.69814654, 0.97016248, 0.71725408, 0.87702738, 0.76615487, 0.57871812, 0.53222417, 0.9976855, 0.80930099, 0.50962849, 0.94555126]


### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [16]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])

In [17]:
lst_3d = [y for i in b for x in i for y in x]

print(lst_3d)

[0.55867166, 0.06210792, 0.08147297, 0.82579068, 0.91512478, 0.06833034, 0.05440634, 0.65857693, 0.30296619, 0.06769833, 0.96031863, 0.51293743, 0.09143215, 0.71893382, 0.45850679, 0.58256464, 0.59005654, 0.56266457, 0.71600294, 0.87392666, 0.11434044, 0.8694668, 0.65669313, 0.10708681, 0.07529684, 0.46470767, 0.47984544, 0.65368638, 0.14901286, 0.23760688]


In [18]:
lst_3d = [x for i in b for y in i for x in y]

print(lst_3d)

[0.55867166, 0.06210792, 0.08147297, 0.82579068, 0.91512478, 0.06833034, 0.05440634, 0.65857693, 0.30296619, 0.06769833, 0.96031863, 0.51293743, 0.09143215, 0.71893382, 0.45850679, 0.58256464, 0.59005654, 0.56266457, 0.71600294, 0.87392666, 0.11434044, 0.8694668, 0.65669313, 0.10708681, 0.07529684, 0.46470767, 0.47984544, 0.65368638, 0.14901286, 0.23760688]


In [19]:
lst_3d = []

for i in b:
    for y in i:
        for x in y:
            lst_3d.append(x)

print(lst_3d)

[0.55867166, 0.06210792, 0.08147297, 0.82579068, 0.91512478, 0.06833034, 0.05440634, 0.65857693, 0.30296619, 0.06769833, 0.96031863, 0.51293743, 0.09143215, 0.71893382, 0.45850679, 0.58256464, 0.59005654, 0.56266457, 0.71600294, 0.87392666, 0.11434044, 0.8694668, 0.65669313, 0.10708681, 0.07529684, 0.46470767, 0.47984544, 0.65368638, 0.14901286, 0.23760688]


### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [20]:
lst_3d = [y for i in b for x in i for y in x if y<=0.5]

print(lst_3d)

[0.06210792, 0.08147297, 0.06833034, 0.05440634, 0.30296619, 0.06769833, 0.09143215, 0.45850679, 0.11434044, 0.10708681, 0.07529684, 0.46470767, 0.47984544, 0.14901286, 0.23760688]


### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [30]:
file_list = [f for f in os.listdir('../data') if f.endswith('.csv')]

print(file_list)

['sample_file_3.csv', 'sample_file_1.csv', 'sample_file_2.csv', 'sample_file_0.csv', 'sample_file_5.csv', 'sample_file_6.csv', 'sample_file_9.csv', 'sample_file_7.csv', 'sample_file_8.csv', 'sample_file_4.csv']


### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [22]:
data_sets = [pd.read_csv(os.path.join('../data', f)) for f in file_list]
data = pd.concat(data_sets, axis=0)

print(data.head(10))

          0         1         2         3         4         5         6  \
0  0.376101  0.896590  0.500995  0.381416  0.447730  0.048472  0.094235   
1  0.498192  0.565500  0.152394  0.284232  0.557042  0.417095  0.663465   
2  0.635284  0.247512  0.179986  0.468231  0.911799  0.764209  0.941413   
3  0.647497  0.072412  0.681403  0.977189  0.690953  0.829347  0.236915   
4  0.170792  0.586900  0.029834  0.921923  0.090727  0.592746  0.972429   
0  0.276827  0.260054  0.942397  0.113187  0.781355  0.475740  0.152061   
1  0.995885  0.158381  0.244274  0.962163  0.651900  0.930665  0.577190   
2  0.641917  0.821055  0.392437  0.782617  0.510762  0.428320  0.017324   
3  0.806532  0.569258  0.148175  0.809987  0.459632  0.735762  0.730664   
4  0.311185  0.501165  0.365979  0.782807  0.776795  0.797199  0.791946   

          7         8         9        10        11        12        13  \
0  0.986890  0.582352  0.037230  0.130306  0.766153  0.153783  0.199140   
1  0.158188  0.039182  0

### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [23]:
selection = [col for col in data if data[col].median() < 0.48]

print(selection)

['2', '9', '12', '14', '17']


In [24]:
selection = []

for c in data:
    if data[c].median() < 0.48:
        selection.append(c)

print(selection)

['2', '9', '12', '14', '17']


### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [25]:
print(data.iloc[:10, :])

          0         1         2         3         4         5         6  \
0  0.376101  0.896590  0.500995  0.381416  0.447730  0.048472  0.094235   
1  0.498192  0.565500  0.152394  0.284232  0.557042  0.417095  0.663465   
2  0.635284  0.247512  0.179986  0.468231  0.911799  0.764209  0.941413   
3  0.647497  0.072412  0.681403  0.977189  0.690953  0.829347  0.236915   
4  0.170792  0.586900  0.029834  0.921923  0.090727  0.592746  0.972429   
0  0.276827  0.260054  0.942397  0.113187  0.781355  0.475740  0.152061   
1  0.995885  0.158381  0.244274  0.962163  0.651900  0.930665  0.577190   
2  0.641917  0.821055  0.392437  0.782617  0.510762  0.428320  0.017324   
3  0.806532  0.569258  0.148175  0.809987  0.459632  0.735762  0.730664   
4  0.311185  0.501165  0.365979  0.782807  0.776795  0.797199  0.791946   

          7         8         9        10        11        12        13  \
0  0.986890  0.582352  0.037230  0.130306  0.766153  0.153783  0.199140   
1  0.158188  0.039182  0

In [26]:
data['20'] = [i for i in data['19'] - 0.1]

print(data[['19', '20']].head(10))

         19        20
0  0.213938  0.113938
1  0.310951  0.210951
2  0.396453  0.296453
3  0.026952 -0.073048
4  0.931145  0.831145
0  0.286542  0.186542
1  0.572232  0.472232
2  0.489528  0.389528
3  0.246594  0.146594
4  0.479022  0.379022


In [27]:
data['20'] = pd.Series(data['19'] - 0.1)

print(data[['19', '20']].head(10))

         19        20
0  0.213938  0.113938
1  0.310951  0.210951
2  0.396453  0.296453
3  0.026952 -0.073048
4  0.931145  0.831145
0  0.286542  0.186542
1  0.572232  0.472232
2  0.489528  0.389528
3  0.246594  0.146594
4  0.479022  0.379022


### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.

In [28]:
extract_07075 = [x[0] for col in data.columns for x in data[[col]].values if (x > 0.7) & (x < 0.75)]

print(extract_07075)

[0.7347510852128797, 0.7025657075988269, 0.7280006345208285, 0.7132714209987683, 0.7258310816144985, 0.736029494090402, 0.7472962776291713, 0.7343092314001137, 0.7358941798147411, 0.7365416322783028, 0.7088042362916818, 0.7329024831531535, 0.7023481768180954, 0.7476323136755818, 0.7008930873050235, 0.7133695725698419, 0.7357618655811269, 0.7013619954419494, 0.7268545088531969, 0.7150799992177622, 0.7173964318670598, 0.7032248108904495, 0.7306642125209889, 0.7124169515124726, 0.71223975981198, 0.7383982036983279, 0.7298115760258881, 0.7051334608870933, 0.7321333453970806, 0.7178166705957928, 0.7374449181749492, 0.7159290265157912, 0.7294980584878026, 0.7215147068185102, 0.7045750112959754, 0.7111584953876777, 0.7209375615129192, 0.7396561066717461, 0.7303553716733908, 0.7133690799930356, 0.7356923324968598, 0.7390312927111312, 0.7078738356977186, 0.7321533684342264, 0.7490680818183477, 0.7130781095091867, 0.7085098152301276, 0.7196096371031628, 0.7264121114538001, 0.7393833032570581, 0.

In [29]:
extract_07075 = []

for col in data.columns: 
    for x in data[[col]].values: 
        if (x > 0.7) & (x < 0.75):
            extract_07075.append(x[0])

print(extract_07075)

[0.7347510852128797, 0.7025657075988269, 0.7280006345208285, 0.7132714209987683, 0.7258310816144985, 0.736029494090402, 0.7472962776291713, 0.7343092314001137, 0.7358941798147411, 0.7365416322783028, 0.7088042362916818, 0.7329024831531535, 0.7023481768180954, 0.7476323136755818, 0.7008930873050235, 0.7133695725698419, 0.7357618655811269, 0.7013619954419494, 0.7268545088531969, 0.7150799992177622, 0.7173964318670598, 0.7032248108904495, 0.7306642125209889, 0.7124169515124726, 0.71223975981198, 0.7383982036983279, 0.7298115760258881, 0.7051334608870933, 0.7321333453970806, 0.7178166705957928, 0.7374449181749492, 0.7159290265157912, 0.7294980584878026, 0.7215147068185102, 0.7045750112959754, 0.7111584953876777, 0.7209375615129192, 0.7396561066717461, 0.7303553716733908, 0.7133690799930356, 0.7356923324968598, 0.7390312927111312, 0.7078738356977186, 0.7321533684342264, 0.7490680818183477, 0.7130781095091867, 0.7085098152301276, 0.7196096371031628, 0.7264121114538001, 0.7393833032570581, 0.